In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# sns.set()

In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense , Input, Flatten

In [3]:
(X_train,y_train),(X_test,y_test)= keras.datasets.mnist.load_data()

In [5]:
# Normalize the Data
X_train,X_test = X_train/255.0, X_test/255.0


In [11]:
def my_ann(): 
        # pass all the layers as list inside the Sequential layer
        model= Sequential([
        Input(shape=(28,28)),
        Flatten(),
        Dense(units=512,activation='relu'),
        Dense(units=512,activation='relu'),
        Dense(units=512,activation='relu'),
        Dense(units=512,activation='relu'),
        Dense(units=10,activation='softmax')
        ])
        model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
        return model


In [13]:
mnist= my_ann()

In [15]:
mnist.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │         5,130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,195,018 (4.56 MB)

 Trainable params: 1,195,018 (4.56 MB)

 Non-trainable params: 0 (0.00 B)

In [17]:
history=mnist.fit(X_train,y_train,epochs=2,batch_size= 64)

Epoch 1/2
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.8873 - loss: 0.3640
Epoch 2/2
938/938 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.9730 - loss: 0.0950


# Weights and biases

In [19]:
mnist.get_weights()

[array([[ 0.02101278, -0.02795844, -0.0622242 , ...,  0.0443968 ,
         -0.02206866,  0.03969198],
        [-0.06681962, -0.01479806, -0.03544186, ...,  0.01961961,
          0.00230405, -0.00463282],
        [-0.02651666,  0.00921649, -0.00701717, ...,  0.01546995,
          0.06433021, -0.00812752],
        ...,
        [ 0.00220793, -0.03382601,  0.04165249, ...,  0.02872668,
         -0.00411077, -0.04187102],
        [-0.02321892, -0.05843942, -0.0426103 , ...,  0.06304453,
         -0.00542397, -0.06141108],
        [ 0.04945508, -0.04977982,  0.04060268, ..., -0.04557758,
          0.05381919,  0.05420189]], dtype=float32),
 array([-8.94415565e-03,  1.76160783e-02, -3.31998169e-02, -3.85093782e-03,
         1.81958135e-02, -3.08832806e-03, -3.43448408e-02,  8.10736977e-03,
        -6.98627252e-03,  7.44674355e-03, -1.16131948e-02, -2.62586884e-02,
        -3.05023845e-02,  2.37346347e-03, -3.30357142e-02, -1.34588014e-02,
         1.62670035e-02,  1.96234267e-02, -2.69789938e

In [21]:
mnist.get_weights()[0]

array([[ 0.02101278, -0.02795844, -0.0622242 , ...,  0.0443968 ,
        -0.02206866,  0.03969198],
       [-0.06681962, -0.01479806, -0.03544186, ...,  0.01961961,
         0.00230405, -0.00463282],
       [-0.02651666,  0.00921649, -0.00701717, ...,  0.01546995,
         0.06433021, -0.00812752],
       ...,
       [ 0.00220793, -0.03382601,  0.04165249, ...,  0.02872668,
        -0.00411077, -0.04187102],
       [-0.02321892, -0.05843942, -0.0426103 , ...,  0.06304453,
        -0.00542397, -0.06141108],
       [ 0.04945508, -0.04977982,  0.04060268, ..., -0.04557758,
         0.05381919,  0.05420189]], dtype=float32)

In [23]:
mnist.get_weights()[1]

array([-8.94415565e-03,  1.76160783e-02, -3.31998169e-02, -3.85093782e-03,
        1.81958135e-02, -3.08832806e-03, -3.43448408e-02,  8.10736977e-03,
       -6.98627252e-03,  7.44674355e-03, -1.16131948e-02, -2.62586884e-02,
       -3.05023845e-02,  2.37346347e-03, -3.30357142e-02, -1.34588014e-02,
        1.62670035e-02,  1.96234267e-02, -2.69789938e-02,  1.95979653e-03,
       -2.56468616e-02, -1.45068215e-02,  1.00724278e-02, -2.06537340e-02,
        4.19501634e-03,  1.44964736e-02,  4.90611698e-03, -6.24319213e-03,
        6.62867865e-03,  1.41452188e-02, -2.80916393e-02, -1.16327582e-02,
       -1.88798625e-02, -2.55104969e-03, -2.11161114e-02, -2.70830654e-02,
       -3.20035703e-02,  4.48820507e-03, -9.65412706e-03,  3.49478261e-03,
       -1.25390086e-02, -2.31722612e-02, -5.98841300e-03, -1.76721625e-02,
       -8.83068237e-03,  2.32731737e-03, -1.39626507e-02, -1.20695876e-02,
       -1.01129534e-02,  9.96303372e-03, -3.86486342e-03, -4.53511067e-03,
        1.64480954e-02,  

In [25]:
for layer in mnist.layers:
    weights = layer.get_weights()  # Returns a list of numpy arrays
    print(f"Layer: {layer.name}")
    if weights:  # Only print if the layer has weights
        for i, weight in enumerate(weights):
            print(f"Weight {i}: {weight.shape}")
            print(weight)  # Or print a summary like np.mean(weight), np.std(weight), etc.
    else:
        print("No weights in this layer")

Layer: flatten
No weights in this layer
Layer: dense
Weight 0: (784, 512)
[[ 0.02101278 -0.02795844 -0.0622242  ...  0.0443968  -0.02206866
   0.03969198]
 [-0.06681962 -0.01479806 -0.03544186 ...  0.01961961  0.00230405
  -0.00463282]
 [-0.02651666  0.00921649 -0.00701717 ...  0.01546995  0.06433021
  -0.00812752]
 ...
 [ 0.00220793 -0.03382601  0.04165249 ...  0.02872668 -0.00411077
  -0.04187102]
 [-0.02321892 -0.05843942 -0.0426103  ...  0.06304453 -0.00542397
  -0.06141108]
 [ 0.04945508 -0.04977982  0.04060268 ... -0.04557758  0.05381919
   0.05420189]]
Weight 1: (512,)
[-8.94415565e-03  1.76160783e-02 -3.31998169e-02 -3.85093782e-03
  1.81958135e-02 -3.08832806e-03 -3.43448408e-02  8.10736977e-03
 -6.98627252e-03  7.44674355e-03 -1.16131948e-02 -2.62586884e-02
 -3.05023845e-02  2.37346347e-03 -3.30357142e-02 -1.34588014e-02
  1.62670035e-02  1.96234267e-02 -2.69789938e-02  1.95979653e-03
 -2.56468616e-02 -1.45068215e-02  1.00724278e-02 -2.06537340e-02
  4.19501634e-03  1.4496473